import type { TipoEventoHistorico } from '../types';

export const rotuloEventoHistorico: Record<TipoEventoHistorico, string> = {
    ORCAMENTO_CRIADO: 'Orçamento criado',
    ORCAMENTO_ALTERADO: 'Orçamento alterado',
    ORCAMENTO_ENVIADO: 'Orçamento enviado',
    ORCAMENTO_APROVADO: 'Orçamento aprovado',
    ORCAMENTO_PERDIDO: 'Orçamento perdido',
    ORCAMENTO_EXPIRADO: 'Orçamento expirado',
    ORCAMENTO_MOVIDO_PIPELINE: 'Orçamento movido no pipeline',
    ORCAMENTO_ITEM_ADICIONADO: 'Item adicionado ao orçamento',
    ORCAMENTO_ITEM_REMOVIDO: 'Item removido do orçamento',
    ORCAMENTO_LINHA_EDITADA: 'Valor do orçamento revisado',
    ORCAMENTO_REVISAO: 'Orçamento reaberto para revisão',
    ORCAMENTO_ALTERACAO_SOLICITADA: 'Cliente pediu alteração no orçamento',
    ORCAMENTO_ESTIMATIVA_ENVIADA: 'Estimativa de preço enviada',
    ORCAMENTO_REABERTO: 'Orçamento perdido reaberto',
    ORDEM_SERVICO_CRIADA: 'Ordem de serviço criada',
    SOLICITACAO_DESCARTADA: 'Solicitação descartada',
    TABELA_PRECO_ATUALIZADA: 'Tabela de preços atualizada',
    PARAMETRO_CALCULO_ATUALIZADO: 'Parâmetros de cálculo atualizados',
    INSTALACAO_AGENDADA: 'Data de instalação proposta',
    INSTALACAO_REAGENDADA: 'Nova data de instalação proposta',
    INSTALACAO_CONFIRMADA_CLIENTE: 'Cliente confirmou a instalação',
    INSTALACAO_RECUSADA_CLIENTE: 'Cliente recusou a data de instalação',
    INSTALACAO_CONTRAPROPOSTA_CLIENTE: 'Cliente sugeriu outra data de instalação',
    INSTALACAO_CONTRAPROPOSTA_ACEITA: 'Contraproposta de instalação aceita',
    INSTALACAO_CONTRAPROPOSTA_RECUSADA: 'Sugestão de instalação recusada — nova data proposta',
    INSTALACAO_CONFIRMADA_MANUAL: 'Instalação confirmada manualmente',
    INSTALACAO_REAGENDAMENTO_NECESSARIO: 'Instalação precisa de nova data',
    INSTALACAO_CANCELADA: 'Instalação cancelada',
    INSTALACAO_REALIZADA: 'Instalação realizada',
    INSTALACAO_CANCELAMENTO_SOLICITADO: 'Cliente pediu para cancelar a instalação',
    INSTALACAO_DATA_MANTIDA: 'Data de instalação mantida',
    MEDICAO_AGENDADA: 'Data de medição proposta',
    MEDICAO_REAGENDADA: 'Nova data de medição proposta',
    MEDICAO_CONFIRMADA_CLIENTE: 'Cliente confirmou a medição',
    MEDICAO_RECUSADA_CLIENTE: 'Cliente recusou a data de medição',
    MEDICAO_CONTRAPROPOSTA_CLIENTE: 'Cliente sugeriu outra data de medição',
    MEDICAO_CONTRAPROPOSTA_ACEITA: 'Contraproposta de medição aceita',
    MEDICAO_CONTRAPROPOSTA_RECUSADA: 'Sugestão de medição recusada — nova data proposta',
    MEDICAO_CONFIRMADA_MANUAL: 'Medição confirmada manualmente',
    MEDICAO_REAGENDAMENTO_NECESSARIO: 'Medição precisa de nova data',
    MEDICAO_CANCELADA: 'Medição cancelada',
    MEDICAO_REALIZADA: 'Medição realizada',
    MEDICAO_CANCELAMENTO_SOLICITADO: 'Cliente pediu para cancelar a medição',
    MEDICAO_DATA_MANTIDA: 'Data de medição mantida',
    ATENDIMENTO_ESCALADO_ATENDENTE: 'Atendimento escalado para atendente',
    ATENDIMENTO_ASSUMIDO: 'Atendimento assumido',
    ATENDIMENTO_ENCERRADO: 'Atendimento encerrado',
    ATENDIMENTO_TRANSFERIDO: 'Atendimento transferido',
    ATENDIMENTO_DEVOLVIDO_BOT: 'Atendimento devolvido ao robô',
    ATENDIMENTO_REABERTO: 'Atendimento reaberto',
    MENSAGEM_NAO_ENTREGUE: 'Mensagem não entregue',
};
