ALTER TABLE medicao
    ADD COLUMN versao BIGINT NOT NULL DEFAULT 0;

ALTER TABLE instalacao
    ADD COLUMN versao BIGINT NOT NULL DEFAULT 0;

ALTER TABLE orcamento
    ADD COLUMN versao BIGINT NOT NULL DEFAULT 0;
